### ISSUE TITLE
hello i m running this code in jupyter notebook bt it is giving error plz can u tell me how i shld debug this i tried all ways for this

### ISSUE THREAD

**Issue by bilkarpooja** [AayushG159/Plant-Leaf-Identification#3]
error                                     Traceback (most recent call last)
<ipython-input-4-bff05af9b77d> in <module>
      1 main_img = cv2.imread(test_img_path)
----> 2 img = cv2.cvtColor(main_img, cv2.COLOR_BGR2RGB)
      3 plt.imshow(img)

error: OpenCV(3.4.1) C:\Miniconda3\conda-bld\opencv-suite_1533128839831\work\modules\imgproc\src\color.cpp:11115: error: (-215) scn == 3 || scn == 4 in function cv::cvtColor

**Comment by AayushG159** [comment]
Hi,
Can you provide a proper documentation of the exact problem along with a supporting picture. Also do check if you are able to load main_img (ie, line 1). If not, then there is an issue with test img path
