### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by Sushmithan52** [AayushG159/Plant-Leaf-Identification#4]
Where can v find dataset?

**Comment by VShalini1219** [comment]
download the flavia dataset from the following link 

https://sourceforge.net/projects/flavia/files/Leaf%20Image%20Dataset/1.0/Leaves.tar.bz2/download

**Comment by Sushmithan52** [comment]
Thanks

**Comment by AayushG159** [comment]
Here you go: http://flavia.sourceforge.net/

Edit: Sorry for the delay
